# Generated by Django 3.0 on 2019-12-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191213_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('jersey_num', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('highest_score', models.PositiveSmallIntegerField(default=0)),
                ('fifties', models.PositiveSmallIntegerField(default=0)),
                ('hundreds', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TeamModel')),
            ],
        ),
    ]
