# Generated by Django 3.0 on 2019-12-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_playermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NTP', max_length=3)),
                ('time', models.DateTimeField()),
                ('teams', models.ManyToManyField(related_name='matches', to='stats.TeamModel')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TeamModel')),
            ],
        ),
    ]
