# Generated by Django 3.0 on 2019-12-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_matchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.TeamModel'),
        ),
    ]
